version: "3"

services:
  mongo-db:
    image: mongo:3.4
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - db-data:/var/lib/mongo

  listremainder:
    image: listremainder:latest
    hostname: listremainder
    environment:
      SPRING_DATASOURCE_URL: mongodb://mongo-db:27017/productsBD
    depends_on:
      - mongo-db
    ports:
      - "9090:9090"

volumes:
  db-data:
