server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${SPRING_DATASOURCE_URL}

logging:
  pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS"} %highlight([%p]) %green([%t]) %yellow(%M\(%F:%L\)) - %msg%n'

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus